RedHatInsights/approval-ui

src/PresentationalComponents/Request/RequestsFilterToolbar.js, src/PresentationalComponents/Workflow/WorkflowsFilterToolbar.js, src/redux/Actions/RequestActions.js, src/redux/Actions/WorkflowActions.js, src/redux/reducers/requestReducer.js, src/redux/reducers/workflowReducer.js
Some of the files were not added during the initial commit.
=> Add files missing from the initial commit

README.md, config/base.webpack.plugins.js, config/dev.webpack.config.js, config/spandx.config.js, config/webpack.common.js, package-lock.json, src/entry-dev.js, src/entry.js, src/index.html
Fixed webpack configuration to match cloud deployment requirements.
=> Migrated ui deployment to cloud.

package.json, src/entry-dev.js
- fix missing character in beta env.
- fix missing env variable for prod build
That should fix UI issues on beta env
cc @karelhala
=> Fixed prod/beta build.

src/smart-components/workflow/workflow-table-helpers.js, src/smart-components/workflow/workflows.js
**Description**
Refactors workflows component to hook component
**TODO**
~~test (next week)~~
@Hyperkid123
=> Refactors workflows to hook component

package-lock.json, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests.js
**Description**
Refactors requests component to hook component
@Hyperkid123
=> Refactors requests component to hook component

src/presentational-components/shared/table-toolbar-view.js, src/smart-components/request/requests.js, src/smart-components/workflow/workflows.js
**Description**
Requests and Workflows are basically the same component, thus I merge them together.
Pros:
- One logic = less code = less bugs
- They behave and look same
- We can split the main component into smaller one if we need to
@Hyperkid123
=> Unify table and toolbar as one component (workflows, requests)

src/smart-components/request/request-detail/action.js, src/smart-components/request/request-detail/request-stage-transcript.js, src/smart-components/request/request-detail/stage.js
- should be merged after #24 
Added transcript list of action comments for each request Stage.
=> List the action transcripts for each Request stage  ( Request Detail Page)

src/smart-components/workflow/workflows.js
Fixes https://github.com/ManageIQ/approval-ui/issues/27
**Description**
Fixes double kebabs in Workflows table
**Before**
**After**
@Hyperkid123
=> Fix double kebabs in Workflows

src/App.js, src/App.scss, src/presentational-components/shared/breadcrubms.js, src/presentational-components/shared/loader-placeholders.js, src/presentational-components/shared/table-toolbar-view.js, src/presentational-components/shared/top-toolbar.js, src/presentational-components/shared/top-toolbar.scss, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/requests.js, src/smart-components/workflow/workflows.js
Add breadcrumbs for the Request tab
=> Add breadcrumb to the Request detail page

src/index.html
Update title to just the App name
=> Update title to just the App name

src/Routes.js
Updated the default landing page to the Requests list page instead of the workflows list page.
https://projects.engineering.redhat.com/browse/SSP-358
=> Updated the default landing page to the Requests list page.

src/presentational-components/shared/table-toolbar-view.js, src/smart-components/workflow/workflows.js
The approval list is selectable ( although the common action, 'Delete' is not yet implemented - will be in a follow-up PR), the requests list is not selectable.
=> Add isSelectable parameter for the TableToolbarView

src/smart-components/workflow/add-workflow-modal.js, src/smart-components/workflow/workflows.js
Fix the initialize and save for the Workflow edit dialog.
Fixes https://projects.engineering.redhat.com/browse/SSP-365
=> Update the  Workflow Edit dialog

src/presentational-components/shared/loader-placeholders.js, src/presentational-components/shared/table-toolbar-view.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/stage-list.js, src/smart-components/request/requests.js
Load placeholder for the Request detail page:
=> Add loader placeholder for the Request/Workflows list

package-lock.json, package.json, src/App.js
Add react-intl package  - will need this in the multi-workflow removal PR
=> Add react-intl package 

src/helpers/workflow/workflow-helper.js, src/presentational-components/shared/table-toolbar-view.js, src/redux/actions/workflow-actions.js, src/smart-components/workflow/remove-workflow-modal.js, src/smart-components/workflow/workflows.js, src/test/smart-components/workflow/__snapshots__/workflows.test.js.snap, src/test/smart-components/workflow/workflows.test.js
Add a 'Delete' button to the toolbar for the Workflows tab to allow the removal of the selected items in the list.
=> Delete multiple selected workflows

src/smart-components/request/expandable-content.js, src/smart-components/request/request-table-helpers.js, src/utilities/store.js
Add 'Reason' to the request expandable content.
Update package versions.
=> Add 'Reason' to the request expandable content

src/presentational-components/shared/table-toolbar-view.js
Add an id for the approval tabs' sections - 'tab-title'
https://projects.engineering.redhat.com/browse/SSP-557
=> Add an id for the approval tabs' sections

src/presentational-components/shared/table-toolbar-view.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests.js, src/smart-components/workflow/workflow-table-helpers.js, src/smart-components/workflow/workflows.js, src/test/smart-components/request/__snapshots__/requests.test.js.snap
Fix workflow and request filtering.
Fixes https://projects.engineering.redhat.com/browse/SSP-493
=> Fix workflow and request filtering

package-lock.json, package.json, src/App.scss, src/forms/edit-workflow-form.schema.js, src/presentational-components/shared/loader-placeholders.js, src/redux/reducers/workflow-reducer.js, src/smart-components/workflow/add-stages/add-stages-wizard.js, src/smart-components/workflow/add-stages/set-stages.js, src/smart-components/workflow/add-stages/stage-information.js, src/smart-components/workflow/add-stages/summary-content.js, src/smart-components/workflow/edit-workflow-modal.js, src/smart-components/workflow/workflows.js, src/test/smart-components/request/__snapshots__/requests.test.js.snap, src/test/smart-components/workflow/__snapshots__/workflows.test.js.snap
Separate the menu item for edit workflow into 2:
1. Edit workflow info -  name and description
2. Edit stages 
https://projects.engineering.redhat.com/browse/SSP-541
=> Separate Edit Workflow into Edit Info and Edit stages

src/helpers/group/group-helper.js, src/smart-components/workflow/add-stages/add-stages-wizard.js, src/smart-components/workflow/add-stages/set-stages.js, src/smart-components/workflow/edit-workflow-modal.js, src/smart-components/workflow/remove-workflow-modal.js
Fixed initial values for stages on Edit workflow. 
Fixed closing the modal after removing a workflow.
=> Fixed initial values for stages on Edit workflow. Fix closing the Removal workflow.

.eslintrc, src/forms/request-comment-form.schema.js, src/helpers/group/group-helper.js, src/helpers/request/request-helper.js, src/helpers/workflow/workflow-helper.js, src/presentational-components/shared/pf4-select-wrapper.js, src/presentational-components/shared/table-toolbar-view.js, src/smart-components/request/request-detail/stage.js, src/smart-components/workflow/add-stages/set-stages.js, src/smart-components/workflow/edit-workflow-modal.js
I've added cons rule for this project which was missing for some reason.
=> Enabled prefer-const eslint rule.

src/App.scss, src/helpers/shared/pagination.js, src/presentational-components/shared/filter-toolbar-item.js, src/presentational-components/shared/loader-placeholders.js, src/presentational-components/shared/table-toolbar-view.js, src/presentational-components/shared/top-toolbar.js, src/smart-components/app-tabs/app-tabs.js, src/smart-components/request/requests.js, src/smart-components/workflow/add-stages/add-stages-wizard.js, src/smart-components/workflow/remove-workflow-modal.js, src/smart-components/workflow/workflows.js, src/test/presentional-components/shared/__snapshots__/filter-toolbar-item.test.js.snap, src/test/presentional-components/shared/filter-toolbar-item.test.js
- Fixes the refresh for the workflows list after an add/remove/update 
- Fixes the content loader display while data is loading - (workflows and requests)
- Fixes the searchbox styling:
=> Fix the refresh for the workflows list after an add/remove/update 

package-lock.json, package.json, src/App.scss, src/presentational-components/shared/breadcrubms.js, src/presentational-components/shared/loader-placeholders.js, src/presentational-components/shared/table-toolbar-view.js, src/presentational-components/shared/top-toolbar.js, src/smart-components/app-tabs/app-tabs.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/requests.js, src/test/presentional-components/shared/__snapshots__/filter-toolbar-item.test.js.snap, src/test/presentional-components/shared/__snapshots__/pf4-select-wrapper.test.js.snap
Fixes the header and lists layout as described in this doc or RBAC:
https://projects.engineering.redhat.com/browse/SSP-792
=> Fixes header and placeholders layout

package-lock.json, package.json, src/smart-components/request/action-modal.js, src/smart-components/request/request-detail/action-transcript.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/request-info-bar.js, src/smart-components/request/requests.js, src/smart-components/workflow/add-stages/add-stages-wizard.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/smart-components/workflow/edit-workflow-stages-modal.js
Update display of request comments list, requester field
Fixes:
https://projects.engineering.redhat.com/browse/SSP-494
https://projects.engineering.redhat.com/browse/SSP-549
=> Update display of request comments list, requester field

config/spandx.config.js, config/webpack.common.js
=> Remove hybrid from webpack.common.js and spandx config

src/helpers/workflow/workflow-helper.js, src/presentational-components/shared/table-toolbar-view.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/smart-components/workflow/edit-workflow-stages-modal.js, src/test/smart-components/workflow/add-stages/__snapshots__/add-stages-wizard.test.js.snap, src/test/smart-components/workflow/add-stages/__snapshots__/set-stages.test.js.snap, src/test/smart-components/workflow/add-stages/__snapshots__/stage-information.test.js.snap, src/test/smart-components/workflow/add-stages/__snapshots__/summary-content.test.js.snap, src/test/smart-components/workflow/add-stages/add-stages-wizard.test.js, src/test/smart-components/workflow/add-stages/set-stages.test.js, src/test/smart-components/workflow/add-stages/stage-information.test.js, src/test/smart-components/workflow/add-stages/summary-content.test.js
Refresh list after the edit info/edit stages completed.
=> Fix workflow list refresh after edit info/stages

src/test/utilities/async-debounce.test.js, src/test/utilities/store.test.js
Added tests for `src/utilities`
=> Test utilities

src/helpers/shared/user-login.js
=> Added axios error interceptor

src/smart-components/workflow/add-stages/set-stages.js, src/smart-components/workflow/add-stages/stage-information.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/smart-components/workflow/edit-workflow-stages-modal.js, src/smart-components/workflow/expandable-content.js, src/smart-components/workflow/remove-workflow-modal.js, src/smart-components/workflow/workflow-table-helpers.js, src/smart-components/workflow/workflows.js, src/test/smart-components/workflow/__snapshots__/workflows.test.js.snap, src/test/smart-components/workflow/add-stages/__snapshots__/set-stages.test.js.snap, src/test/smart-components/workflow/add-stages/add-stages-wizard.test.js, src/test/smart-components/workflow/add-stages/edit-workflow-info-modal.test.js, src/test/smart-components/workflow/add-stages/set-stages.test.js, src/test/smart-components/workflow/edit-workflow-stages-modal.test.js, src/test/smart-components/workflow/remove-workflow-modal.test.js, src/test/smart-components/workflow/workflow-table-helpers.test.js, src/test/smart-components/workflow/workflows.test.js
Added tests to workflow components.
=> Smart components workflow tests

.eslintrc, src/presentational-components/shared/loader-placeholders.js, src/smart-components/request/action-modal.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/stage-list.js, src/smart-components/request/request-detail/stage.js, src/smart-components/workflow/add-stages/add-stages-wizard.js, src/smart-components/workflow/add-stages/summary-content.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/smart-components/workflow/edit-workflow-stages-modal.js, src/smart-components/workflow/remove-workflow-modal.js, src/smart-components/workflow/workflows.js, src/test/smart-components/request/action-modal.test.js, src/test/smart-components/request/request-detail/__snapshots__/stage.test.js.snap, src/test/smart-components/request/request-detail/request-detail.test.js, src/test/smart-components/request/request-detail/stage-list.test.js, src/test/smart-components/request/request-detail/stage.test.js
- Added tests for `smart-components/request` files
- Added react/jsx-equals-spacing` eslint rule
- Fixed loading state in stage-list component
- moved isExpanded function call from stage-list to parent component (reduced multiple function calls to one)
=> Smart components requests tests

.dependabot/config.yml
Added weekly interval between dependabot PR updates
=> Restrict dependabot pr interval

src/smart-components/workflow/workflow-table-helpers.js, src/smart-components/workflow/workflows.js, src/test/smart-components/workflow/workflow-table-helpers.test.js
Add the sequence column to the workflows list:
=> Add the sequence column to the workflow list

src/helpers/request/request-helper.js, src/helpers/workflow/workflow-helper.js, src/presentational-components/shared/filter-toolbar-item.js, src/presentational-components/shared/loader-placeholders.js, src/presentational-components/shared/table-toolbar-view.js, src/presentational-components/shared/top-toolbar.js, src/redux/actions/request-actions.js, src/redux/actions/workflow-actions.js, src/redux/reducers/request-reducer.js, src/smart-components/common/async-pagination.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests.js, src/smart-components/workflow/workflow-table-helpers.js, src/smart-components/workflow/workflows.js, src/test/presentional-components/shared/__snapshots__/filter-toolbar-item.test.js.snap, src/test/presentional-components/table-toolbar-view.test.js, src/test/redux/actions/request-actions.test.js, src/test/redux/actions/workflow-actions.test.js, src/test/smart-components/request/__snapshots__/requests.test.js.snap, src/test/smart-components/workflow/__snapshots__/workflows.test.js.snap, src/test/smart-components/workflow/workflow-table-helpers.test.js, src/test/smart-components/workflow/workflows.test.js, src/utilities/async-debounce.js
Fixed the filter and the pagination for the list of requests and workflows.
Fixed spacing around the Approval title.
Filter workflows:
Filter requests:
/72472173-138dfc00-37b2-11ea-835c-68048b92f228.png)
Pagination:
Placeholders for the requests/workflows table:
=> Fixed filter and pagination the list of requests and workflows

package-lock.json, package.json, src/helpers/shared/helpers.js
=> Use DateFormat instead of moment

package-lock.json, package.json, src/helpers/shared/helpers.js, src/smart-components/request/expandable-content.js, src/smart-components/request/request-detail/action-transcript.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests.js, src/test/smart-components/request/expandable-content.test.js
Updated the approval api js client. 
Updates for the available actions.
Fixes dates for the action transcript:
Before:
After:
=> Update approval js client version. Updated action state's values.

src/smart-components/workflow/add-stages/summary-content.js, src/test/smart-components/workflow/add-stages/__snapshots__/summary-content.test.js.snap
Fix for :
https://projects.engineering.redhat.com/browse/SSP-1078
After:
=> Updated create workflow summary screen - label and heading

src/helpers/request/request-helper.js, src/test/redux/actions/request-actions.test.js, src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap, src/test/smart-components/request/request-detail/request-detail.test.js
For the action transcript - still need to get the  actions for the requests with no subrequests
After - transcript for a request with no subrequests, and one with multiple subrequests:
=> Action transcript - fetch the actions for the requests with no subrequests

src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap, src/test/smart-components/request/request-detail/request.test.js
Tests were failing due to the relative date in the snapshot being different every day.
Remove the date from the snapshot.
=> Updated dates and snapshots for the request test.

src/forms/workflow-form.schema.js, src/redux/actions/workflow-actions.js, src/smart-components/request/requests.js, src/smart-components/workflow/add-stages/add-stages-wizard.js, src/smart-components/workflow/add-stages/stage-information.js, src/smart-components/workflow/add-stages/summary-content.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/smart-components/workflow/edit-workflow-stages-modal.js, src/smart-components/workflow/remove-workflow-modal.js, src/smart-components/workflow/workflows.js, src/test/helpers/shared/user-login.test.js, src/test/redux/actions/workflow-actions.test.js, src/test/redux/reducers/workflow-reducer.test.js, src/test/smart-components/workflow/add-stages/__snapshots__/stage-information.test.js.snap, src/test/smart-components/workflow/add-stages/__snapshots__/summary-content.test.js.snap, src/test/smart-components/workflow/add-stages/add-stages-wizard.test.js, src/test/smart-components/workflow/add-stages/edit-workflow-info-modal.test.js, src/test/smart-components/workflow/remove-workflow-modal.test.js, src/test/smart-components/workflow/workflow-table-helpers.test.js, src/test/smart-components/workflow/workflows.test.js
Build errors fixed in https://github.com/RedHatInsights/approval-ui/pull/142
https://projects.engineering.redhat.com/browse/SSP-1173
=> Rename 'workflows' to 'approval processes'

README.md
=> Replace CodeClimate Badge with Codecov

src/presentational-components/shared/table-empty-state.js, src/presentational-components/shared/table-toolbar-view.js, src/smart-components/request/requests.js, src/smart-components/workflow/workflows.js, src/test/presentional-components/table-toolbar-view.test.js
=> Empty pages for the approval processes and requests lists

src/App.scss, src/presentational-components/shared/bottom-pagination-container.js, src/presentational-components/shared/table-toolbar-view.js, src/test/presentional-components/table-toolbar-view.test.js
https://projects.engineering.redhat.com/browse/SSP-1203
=> Add bottom pagination for workflows and requests pages

src/smart-components/workflow/edit-workflow-info-modal.js
Fixes 
https://projects.engineering.redhat.com/browse/SSP-1275
=> Update cancel notification message for Edit approval process info

src/smart-components/request/requests.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1273
Fixed the id for the add comment modal
=> Update request action check  for the request list

src/redux/actions/workflow-actions.js, src/smart-components/workflow/add-stages/add-stages-wizard.js, src/smart-components/workflow/add-stages/stage-information.js, src/test/redux/actions/workflow-actions.test.js, src/test/smart-components/workflow/add-stages/__snapshots__/add-stages-wizard.test.js.snap, src/utilities/store.js
Update notifications to display the error messages from the endpoint
Use react hooks in add stages modal
Fixes:
https://projects.engineering.redhat.com/browse/SSP-1258
Before - generic error message.
After:
=> Update notifications to display the error messages from the endpoint

src/App.scss, src/smart-components/request/request-detail/action-transcript.js, src/smart-components/workflow/edit-workflow-stages-modal.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1249
=> Updated display text and icons for approval request states

src/smart-components/request/request-detail/request-detail.js, src/test/smart-components/request/request-detail/request-detail.test.js
Follow up to #190. Fixes https://projects.engineering.redhat.com/browse/SSP-1368.
=> Add persona to the request content endpoint

src/Routes.js, src/routing/protected-route.js, src/smart-components/error-pages/common-api-error.js
Add protected routes:
- trying to access the workflows routes by a non-admin will display an unauthorized page ( same as the catalog ) 
Fixes https://projects.engineering.redhat.com/browse/SSP-1365
=> Add protected routes 

src/helpers/group/group-helper.js, src/redux/actions/group-actions.js, src/smart-components/workflow/add-stages/set-stages.js, src/test/redux/actions/group-actions.test.js, src/test/smart-components/workflow/add-stages/add-stages-wizard.test.js, src/test/smart-components/workflow/add-stages/set-stages.test.js, src/test/smart-components/workflow/edit-workflow-stages-modal.test.js, src/test/smart-components/workflow/workflows.test.js
Create/update approval process - list only groups with approval admin or approval approver roles.
=> Create/update approval process - list only groups with approval roles

src/App.scss, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/request-info-bar.js
New mock for the request info bar:
https://marvelapp.com/941d903/screen/59371517
=> Refactor request detail info bar into 2 areas: request and order parameters

src/smart-components/workflow/add-groups/set-groups.js
Fix async group options loading for create/edit approvals
Fixes https://projects.engineering.redhat.com/browse/SSP-1453
=> Fix async group options loading for create/edit approvals

src/smart-components/request/request-detail/request-detail.js, src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap
jira: https://projects.engineering.redhat.com/browse/SSP-1459
This PR adjusts the responsiveness of the grid for different screen sizes. 
Old (desktop)
New (desktop)
Old (mobile)
New (mobile)
=> Request screen - left column responsiveness fix

src/smart-components/workflow/remove-workflow-modal.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1478
Before:
After:
=> Updated styling for the remove approval process modal

src/App.js, src/helpers/request/request-helper.js, src/helpers/shared/helpers.js, src/redux/reducers/request-reducer.js, src/routing/protected-route.js, src/smart-components/error-pages/common-api-error.js, src/smart-components/request/expandable-content.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/request-info-bar.js, src/smart-components/request/request-detail/request-list.js, src/smart-components/request/request-detail/request-transcript.js, src/smart-components/request/request-detail/request.js, src/smart-components/request/requests.js, src/test/redux/actions/request-actions.test.js, src/test/smart-components/request/expandable-content.test.js, src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap, src/test/smart-components/request/request-detail/request-list.test.js, src/test/smart-components/request/request-detail/request.test.js, src/test/smart-components/workflow/workflow-table-helpers.test.js
https://projects.engineering.redhat.com/browse/SSP-1473
Update the request transcript page to show the Approve/Deny/Comment buttons according to the user roles/user_capabilities.
=> Hide/Show action buttons for user/approver/admin

src/smart-components/request/expandable-content.js, src/test/smart-components/request/expandable-content.test.js
Part of SSP-1511
**Before**
**After**
@Hyperkid123 @lgalis
=> Replace FC spinner with patternfly spinner

.eslintrc, src/constants/routes.js, src/presentational-components/shared/breadcrubms.js, src/smart-components/request/action-modal.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/request.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests.js, src/smart-components/workflow/add-groups/add-workflow-wizard.js, src/smart-components/workflow/edit-workflow-groups-modal.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/smart-components/workflow/remove-workflow-modal.js, src/smart-components/workflow/workflows.js, src/test/presentional-components/shared/__snapshots__/breadcrumbs.test.js.snap, src/test/smart-components/request/request-detail/request-detail.test.js, src/test/smart-components/request/request-detail/request.test.js, src/test/smart-components/workflow/__snapshots__/workflows.test.js.snap, src/test/smart-components/workflow/add-groups/edit-workflow-info-modal.test.js, src/test/smart-components/workflow/edit-workflow-stages-modal.test.js, src/test/smart-components/workflow/workflows.test.js, src/utilities/constants.js, src/utilities/use-query.js
SSP-1513
- `useQuery` used from catalog
todo:
@Hyperkid123
=> Use query based routing

src/presentational-components/shared/breadcrubms.js, src/smart-components/request/request-detail/request-detail.js, src/test/presentional-components/shared/__snapshots__/breadcrumbs.test.js.snap, src/test/smart-components/request/request-detail/request-detail.test.js
SSP-1509
**Before**
**After**
@Hyperkid123
=> Fix breadcrumbs

src/redux/actions/workflow-actions.js, src/smart-components/workflow/add-groups/add-workflow-wizard.js, src/smart-components/workflow/workflows.js, src/test/redux/actions/workflow-actions.test.js
Refreshes workflows after the process is created
@Hyperkid123
=> Refresh workflow table after adding a approval procces

src/smart-components/workflow/remove-workflow-modal.js, src/test/smart-components/workflow/remove-workflow-modal.test.js
SSP-1537
I did some little UX
@Hyperkid123
=> Refresh Approval processes table after remove

src/helpers/workflow/workflow-helper.js, src/test/smart-components/workflow/workflows.test.js
Fixed sortBy error in Create approval. Fixed workflow tests.
=> Updated sort query for no sortBy and updated tests

src/App.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/workflow/edit-workflow-groups-modal.js, src/smart-components/workflow/edit-workflow-info-modal.js
Hopefully it will fix SSP-1543
cc @Hyperkid123
=> Import App.scss in App.js

src/App.js, src/Routes.js, src/constants/routes.js, src/smart-components/request/expandable-content.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/request.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests.js, src/smart-components/workflow/edit-workflow-groups-modal.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/test/smart-components/request/request-detail/request.test.js
This is meant to pull in #248 and #253
=> [QA-Beta] Sprint 52 hotfix

src/App.js, src/Routes.js, src/constants/routes.js, src/smart-components/request/expandable-content.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/request.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests.js, src/smart-components/workflow/edit-workflow-groups-modal.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/test/smart-components/request/request-detail/request.test.js
This pulls in changes from #248 and #253
=> [QA-Stable] Sprint 52 hotfix

src/App.js, src/Routes.js, src/constants/routes.js, src/smart-components/request/expandable-content.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/request.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests.js, src/smart-components/workflow/edit-workflow-groups-modal.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/test/smart-components/request/request-detail/request.test.js
This pulls in the changes from #248 and #253
=> [CI-Stable] Sprint 52 hotfix

src/App.scss, src/Routes.js, src/helpers/request/request-helper.js, src/smart-components/app-tabs/app-tabs.js, src/smart-components/request/allrequests.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests-list.js, src/smart-components/request/requests.js, src/smart-components/workflow/workflows.js, src/test/smart-components/request/requests.test.js, src/test/smart-components/workflow/workflows.test.js, src/utilities/constants.js
https://projects.engineering.redhat.com/browse/SSP-1527
Add an All Requests tab.
Part of of the new request list mock - add a column for the request ID and icons for decision.
=> Add all requests tab

src/App.scss, src/presentational-components/shared/top-toolbar.scss
This PR removes unused css styling from the top-toolbar (page title and tab area)
=> Toolbar styling cleanup

src/smart-components/request/action-modal.js, src/smart-components/workflow/add-groups/add-workflow-wizard.js, src/smart-components/workflow/edit-workflow-groups-modal.js, src/smart-components/workflow/edit-workflow-info-modal.js, src/test/smart-components/request/action-modal.test.js, src/test/smart-components/workflow/add-groups/add-workflow-wizard.test.js
jira: https://projects.engineering.redhat.com/browse/SSP-1619
=> Removed cancel notifications from modals.

src/smart-components/app-tabs/app-tabs.js, src/smart-components/request/request-detail/request-detail.js, src/test/smart-components/request/request-detail/request-detail.test.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1602
=> Rename 'Request queue' to 'My requests'

src/Routes.js, src/constants/routes.js, src/presentational-components/shared/table-toolbar-view.js, src/smart-components/request/allrequests.js, src/smart-components/request/request-detail/all-request-detail.js, src/smart-components/request/request-detail/my-request-detail.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/request-list.js, src/smart-components/request/request-detail/request-transcript.js, src/smart-components/request/request-detail/request.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests-list.js, src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap, src/test/smart-components/request/request-detail/all-request-detail.test.js, src/test/smart-components/request/request-detail/request-detail.test.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1623
=> Updated breadcrumbs for the two types of request queues

src/smart-components/request/request-detail/action-transcript.js
Spacing between icons and text was inconsistant.
Jira: https://projects.engineering.redhat.com/browse/SSP-1627
Old
New
=> Fix icon spacing on Request Transcript screen

.eslintrc, .gitignore, package-lock.json, package.json
jira: https://projects.engineering.redhat.com/browse/SSP-1657
To create messages json run npm run extract:messages or yarn extract:messages.
A new file with messages will be created in ./translations/messages.json. It is ignored from the repository since we don't know how and where to send these for translation.
It looks like something likes this:
```jsonb
[
{
"id": "enter-info",
"defaultMessage": "Enter your information"
},
{
"id": "create-approval-process-set-groups",
"defaultMessage": "Set groups"
},
...
]
```
This can then be used to create messages for various locales
=> Add formatjs scraper script

.travis/custom_release.sh
Requires the creation of a new master-stable branch in place of ci-stable and qa-stable.
cc @brahmanim
=> Update custom_release.sh to work with 4 branches

src/smart-components/request/action-modal.js
jira: https://projects.engineering.redhat.com/browse/SSP-1704
=> Fix wrong intl value name.

src/smart-components/common/form-renderer.js, src/smart-components/request/action-modal.js, src/smart-components/workflow/add-workflow-modal.js
Approval part of https://projects.engineering.redhat.com/browse/SSP-1731
=> Disable form submits on pristine in add/edit forms

src/smart-components/workflow/workflows.js
**Before**
**After**
cc @Hyperkid123
=> Update approval processes table column widths

src/smart-components/error-pages/common-api-error.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1746
Unauthorized page - fixed link to the previous page
=> Unauthorized page - fixed link to the previous page

src/smart-components/request/requests-list.js
Add breakWord cell transform for the name column.
Fixes https://projects.engineering.redhat.com/browse/SSP-1747
Before:
After:
=> Fix missing columns caused by the long  request name

src/redux/actions/workflow-actions.js, src/redux/reducers/workflow-reducer.js, src/smart-components/workflow/workflow-table-helpers.js, src/test/redux/reducers/workflow-reducer.test.js, src/test/smart-components/workflow/workflows.test.js
The sequence needs to only be updated for the moving workflow, the backend will update the rest of the sequences as needed.
=> Updated approval process sequence increase/decrease 

package-lock.json, package.json, src/smart-components/request/action-modal.js, src/smart-components/request/request-detail/request-detail.js, src/test/smart-components/request/request-detail/all-request-detail.test.js
Fixes https://projects.engineering.redhat.com/browse/SSP-1575
=> Add refresh request details after action modal

package-lock.json, src/helpers/shared/pagination.js, src/smart-components/workflow/remove-workflow-modal.js, src/smart-components/workflow/workflows.js, src/test/smart-components/workflow/workflows.test.js
Fixes https://issues.redhat.com/browse/SSP-1669.
Updated workflows last page on removal
=> Updated approval processes' last page on removal

src/constants/routes.js, src/messages/action-modal.messages.js, src/messages/requests.messages.js, src/smart-components/common/form-renderer.js, src/smart-components/request/action-modal.js, src/smart-components/request/request-detail/request-detail.js, src/smart-components/request/request-detail/request.js, src/smart-components/request/requests-list.js, src/smart-components/request/requests.js, src/test/smart-components/request/action-modal.test.js, src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap, src/test/smart-components/request/request-detail/all-request-detail.test.js, src/test/smart-components/request/request-detail/request.test.js, src/test/smart-components/request/requests.test.js
Fixes https://issues.redhat.com/browse/SSP-1800
=> Update action modal layout 

src/smart-components/workflow/edit-workflow-modal.js
Fixes https://issues.redhat.com/browse/SSP-1901
=> Fix approval process description clearing

package-lock.json, package.json, src/forms/set-group-select.schema.js
Fixes https://issues.redhat.com/browse/SSP-1944 and https://issues.redhat.com/browse/SSP-1888
=> Fix for the UI crash on selecting groups for approval process create/edit

src/messages/requests.messages.js, src/smart-components/request/request-detail/request.js, src/smart-components/request/requests-list.js
Fixes https://issues.redhat.com/browse/SSP-1965
All request:
My request:
=> Update requests empty page messages

src/presentational-components/shared/no-rows-state.js, src/presentational-components/shared/table-empty-state.js, src/presentational-components/shared/table-toolbar-view.js, src/smart-components/request/EmptyRequestList.js, src/smart-components/request/request-table-helpers.js, src/smart-components/request/requests-list.js, src/smart-components/workflow/workflows.js, src/test/presentional-components/table-toolbar-view.test.js, src/test/smart-components/workflow/workflows.test.js
https://issues.redhat.com/browse/SSP-2025
=> Refactor empty request page

src/forms/set-group-select.schema.js
Fixes https://issues.redhat.com/browse/SSP-2046
Before:
After:
=> Disable current groups in the select dropdown

src/forms/request-comment-form.schema.js, src/smart-components/request/action-modal.js
Fixes https://issues.redhat.com/browse/SSP-2059
=> Do not allow approval empty comments

src/messages/workflows.messages.js, src/smart-components/workflow/workflows.js
Add button to the empty approval processes page to create an approval process. Change icon to the PlusCircleIcon.
Before:
After:
=> Add button to the empty approval processes page to create an approval process

package-lock.json, package.json
This is just to include #523 into the latest that will be going to prod-stable
=> [Prod-beta] Merge main to prod-beta

package-lock.json, package.json
Reverts RedHatInsights/approval-ui#616
=> Revert "Bump @redhat-cloud-services/frontend-components-utilities from 3.2.3 to 3.2.8"

src/presentational-components/navigation/about-modal.js
Fixed path for the logo image in the About modal.
=> Fixed logo path in the about modal

config/standalone.dev.webpack.config.js, config/standalone.prod.webpack.config.js, config/webpack.base.config.js, src/helpers/shared/active-user.js, src/routing/protected-route-s.js, src/utilities/constants.js
Update auth paths per https://github.com/ansible/ansible-catalog/pull/321
=> Update authorization paths 

src/forms/load-groups-debounced.js, src/helpers/group/group-helper.js, src/redux/actions/group-actions.js, src/test/smart-components/workflow/modals/add-workflow-modal-s.test.js
Add roles to the approval modal group list query.
https://issues.redhat.com/browse/SSP-2756
=> Add roles to the approval modal group list query

src/test/smart-components/workflow/modals/add-workflow-modal-s.test.js
Test for https://github.com/RedHatInsights/approval-ui/pull/675
=> Standalone - tests for the approval processes list refresh
