RedHatInsights/approval-ui

src/smart-components/workflow/summary_content.js

Follow up to #10.
Fix the display of the group names on the Add workflow summary screen wizard.

Fix add workflow summary screen

---

config/base.webpack.config.js
config/spandx.config.js
package.json
src/entry-dev.js
src/entry.js

Approval link has changed in chrome. I've updated the routing base path. https://github.com/RedHatInsights/insights-chrome/commit/0893997f1a7637ac4af013e267df82dc6049a184
Also it seems that approval has not been build in a week or so and the css stopped working like in catalog. It was quite odd that the same mistake did not show in approval UI event though it has identical build config.

Fix approval basename

---

src/smart-components/request/request-detail/request-info-bar.js
src/smart-components/request/request-detail/stage.js

Update for the PF4 datalist component that was updated in a previous PR:
Before:
After:
Small change to the Request info bar to display all the request parameters, not filter out the masked password:

Update for pf4 datalist component

---

src/helpers/workflow/workflow-helper.js
src/smart-components/workflow/add-workflow-modal.js
src/smart-components/workflow/expandable-content.js
src/smart-components/workflow/workflow-table-helpers.js

For now, when a group(stage) no longer exist, the ui displays the group's uuid in the workflows list ( expanded content).
This PR clears the group uuid for a group that can no longer be accessed from the Edit Workflow Stage selection and displays a message for this stage/group.

Fix workflow edit for non-existing group stages

---

src/smart-components/app-tabs/app-tabs.js
src/smart-components/request/requests.js
src/smart-components/workflow/workflow-table-helpers.js
src/smart-components/workflow/workflows.js

Update UI to match the Approval UI UX mocks
1. Change ‘Requests’ to ‘Request queue’
2. Use sentence case for  ‘Find a workflow’ and  ‘Create workflow’
3. Remove Groups column from the workflows list

Update UI to match the Approval UI UX mocks - part 1

---

src/smart-components/request/request-table-helpers.js
src/smart-components/request/requests.js

Use the request name instead of the id and the requester_name - as these are now available
Before:
After:

[WIP]Update the name and requester in the requests list

---

src/helpers/group/group-helper.js
src/helpers/workflow/workflow-helper.js
src/smart-components/workflow/add-stages/add-stages-wizard.js
src/smart-components/workflow/add-stages/set-stages.js
src/smart-components/workflow/add-stages/summary-content.js
src/smart-components/workflow/edit-workflow-info-modal.js
src/smart-components/workflow/edit-workflow-stages-modal.js
src/smart-components/workflow/workflows.js
src/test/smart-components/workflow/add-stages/__snapshots__/set-stages.test.js.snap

Replace 'Stage' with 'Group' labels in the Add/edit workflow menu and modals.
https://projects.engineering.redhat.com/browse/SSP-995
Also updated the error handling for the groups that was causing the workflows list to not display.

Fix nonexisting groups errors and replace stage labels with groups

---

src/helpers/request/request-helper.js
src/smart-components/request/request-detail/request-list.js
src/smart-components/request/request-detail/request-transcript.js

Update helper functions to get the subrequests. 
Display the subrequests in the transcript list and apply the actions on subrequests rather than the parent request, when these exist.
Note: at the moment, all requests have the Accept/Deny button - will modify to only have the actions apply to the oldest non-complete subrequest.

Handle requests with sub-requests

---

src/smart-components/request/expandable-content.js
src/smart-components/request/request-table-helpers.js
src/smart-components/request/requests.js

The list of requests will only display the Approve/Deny/Comment action buttons for requests with no sub-requests.
The request detail page displays the Approve/Deny/Comment buttons for all sub-requests not yet complete, or root requests if there are no child requests.

Display action button in the requests expanded rows only for requests with no subrequests

---

src/App.scss
src/presentational-components/shared/table-toolbar-view.js
src/presentational-components/shared/top-toolbar.js
src/smart-components/request/expandable-content.js
src/smart-components/request/request-detail/request-info-bar.js
src/smart-components/request/request-table-helpers.js
src/smart-components/request/requests.js
src/smart-components/workflow/workflows.js

Updated_at column displays the finished_at if available, otherwise notified_at.
Updated content in the expanded request row:
Updated request detail info bar:
Before:
After:
Updated content in the expanded request row:

Fix for updated_at column, other content in the request list and detail page

---

src/smart-components/request/request-table-helpers.js
src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap

Use created_at as a backup date for the updated_at column
Before:
After:

Requests list - Use created_at as a backup date for the updated_at column

---

src/smart-components/request/request-detail/request.js
src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap
src/test/smart-components/request/request-detail/request-list.test.js

Note - failing build is fixed in #142 
https://projects.engineering.redhat.com/browse/SSP-1205
All subrequests have the same 'name' field as the parent request, that is the name of the service ordered. Using the group_name instead of the name for each subrequest in the request detail page transcript.

Request transcript - Use group names for child requests

---

.dependabot/config.yml

It's driving me crazy!
Dependabot should run weekly not all the time.

Remove live update schedule from dependabot.

---

src/smart-components/request/request-detail/request.js
src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap
src/test/smart-components/request/request-detail/request-list.test.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1380
Before:
After:

Request action transcript - use group name for parent requests

---

src/smart-components/request/request-detail/request-detail.js
src/utilities/constants.js

https://projects.engineering.redhat.com/browse/SSP-1167
Return to the same page when closing an action modal.
From the detail page:
From the request list:

Update closeUrl for the action modal

---

src/helpers/shared/user-login.js

https://projects.engineering.redhat.com/browse/SSP-1257
For this PR - using the existing sentryId parameter to display the x-rh-insights-request-id.
This will be changed after the requestId parameter is added to the platform notifications.

Add request id to the error notifications

---

src/smart-components/request/request-table-helpers.js

Jira: https://projects.engineering.redhat.com/browse/SSP-1454
This PR removes the "Button" tag from the request name link, allowing the text to inherit wrapping like other text in the table.
Old
New

fix long request names in requests table

---

src/smart-components/workflow/edit-workflow-groups-modal.js
src/smart-components/workflow/edit-workflow-info-modal.js
src/test/smart-components/workflow/add-groups/edit-workflow-info-modal.test.js
src/test/smart-components/workflow/edit-workflow-stages-modal.test.js
src/utilities/use-workflows.js

SSP-1521
When the workflow is in the table - it's used instead of fetching.
**Before**
**After**
@Hyperkid123

Fetch workflow only if it's not in the table

---

src/Routes.js
src/constants/routes.js
src/smart-components/request/expandable-content.js
src/smart-components/request/request-detail/request-detail.js
src/smart-components/request/request-detail/request.js
src/smart-components/request/request-table-helpers.js
src/smart-components/request/requests.js
src/test/smart-components/request/request-detail/request.test.js

jira: https://projects.engineering.redhat.com/browse/SSP-1541
- the request detail and requests components were sharing routes (both hanged on '/requests')
- components were not chosen based on the route, but based on the query
- this caused that the detail component was eating the list component
- add a separate route for request detail `/request`
- request detail and list components are now independent
- fixed old link pathname for request approve/deny modals in the expandable content
Note: ~~It's possible that the same thing is happening on the workflows. Checking that now.~~ Workflows do not have nested routing

Fixed ambiguous request routing.

---

src/smart-components/request/requests.js
src/smart-components/workflow/workflows.js
src/test/smart-components/workflow/workflows.test.js

Two small UX/UI changes:
1) Dropdown items are buttons - when hovering, there is the click cursor variant
2) Delete button is black now (as in other platform apps)
Before
After
What do you think, @sbuenafe-rh ?

Small UX fixes - dropdown items use buttons, black delete button

---

src/App.scss
src/presentational-components/shared/loader-placeholders.js
src/smart-components/request/request-detail/request-detail.js
src/smart-components/request/request-detail/request-info-bar.js
src/smart-components/request/request-detail/request-transcript.js

This PR adjusts the "Request transcript" header styling  as well as other refactoring.
Old
New

detail pane cleanup

---

src/presentational-components/shared/table-toolbar-view.js
src/smart-components/request/expandable-content.js
src/smart-components/request/request-table-helpers.js
src/smart-components/request/requests-list.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1569
The buttons should be  available in the expanded content only in the Rquest Queue tab, not in All requests

Disable buttons on allrequests tab

---

src/App.scss

Removing the L-R padding override of PF styling better matches the mock
Before
After
Mock up

remove toolbar styling override

---

src/App.scss
src/smart-components/request/expandable-content.js
src/smart-components/request/request-detail/action-transcript.js
src/smart-components/request/request-table-helpers.js
src/smart-components/workflow/add-groups/summary-content.js
src/smart-components/workflow/expandable-content.js
src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap
src/test/smart-components/workflow/add-groups/__snapshots__/summary-content.test.js.snap

This PR replaces the custom "data-table-detail" with standard PF classes.
Before:
After:

remove custom Data list class

---

src/App.scss
src/presentational-components/shared/table-toolbar-view.js

The PR replaces the custom "table-fix" class with a standard PF padding class.
Old
New

Remove custom "table-fix" class

---

src/App.scss
src/smart-components/request/request-detail/request-detail.js

Refactor of "info-bar" and "detail-pane" styling. Adds overflow-wrap fallback support for IE & Safari .
Before
After

detail screen refactor

---

src/helpers/workflow/workflow-helper.js
src/presentational-components/shared/loader-placeholders.js
src/smart-components/workflow/remove-workflow-modal.js
src/test/smart-components/request/request-detail/request-detail.test.js
src/test/smart-components/workflow/remove-workflow-modal.test.js
src/test/smart-components/workflow/workflows.test.js

SSP-1512
**Before**
**After**
Updated according to new design
Single process
Multiple processes
And because users can go directly to the remove modal via URL for single process, there has to be a loading placeholder until the name is loaded.
Buttons are enabled as they are still working fine without the loaded data. But we can disable/hide them too.

[Needs UX] Update remove modal

---

src/presentational-components/shared/table-toolbar-view.js

jira: https://projects.engineering.redhat.com/browse/SSP-1624
- align the dropdown menu to the right edge of the select toggle root

Align mobile view dropdown menu to right.

---

src/smart-components/workflow/edit-workflow-groups-modal.js
src/smart-components/workflow/edit-workflow-info-modal.js
src/smart-components/workflow/remove-workflow-modal.js

This PR fixes an issue where all modals are extremely narrow in the mobile layout, by replacing width of 40% with the small size variant.
Jira: https://projects.engineering.redhat.com/browse/SSP-1625
Old
New

Add variant property to modals

---

src/messages/workflows.messages.js
src/smart-components/workflow/remove-workflow-modal.js
src/test/smart-components/workflow/remove-workflow-modal.test.js
src/utilities/constants.js

Fixes https://projects.engineering.redhat.com/browse/SSP-1606
Add information about apps/object type dependencies to the remove approval process modal.
After: 
with linked resources:
Without linked resources:

Add dependencies message to remove workflow modal

---

src/App.scss

This PR adds space between the filter and pagination in the mobile layout
Jira: https://projects.engineering.redhat.com/browse/SSP-1626
Old
New

mobile requests screen styling fix

---

src/helpers/request/request-helper.js

https://projects.engineering.redhat.com/browse/SSP-1703
- the value was missing in request detail summary card
Before
After

Fetch requester name in transcript query

---

package-lock.json
package.json

FC introduced a prop warning in one of the latest versions (please see https://github.com/RedHatInsights/frontend-components/pull/648 )
```jsx
react_devtools_backend.js:2273 Warning: Unknown event handler property `onShowMore`. It will be ignored.
in input (created by TextInputBase)
in TextInputBase (created by ForwardRef)
in ForwardRef (created by Text)
in Text (created by ConditionalFilter)
in div (created by SplitItem)
in SplitItem (created by ConditionalFilter)
in div (created by Split)
in Split (created by ConditionalFilter)
in ConditionalFilter (created by PrimaryToolbar)
```
```jsx
react_devtools_backend.js:2273 Warning: React does not recognize the `showMoreTitle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase …
```

Bump FC to remove show more title prop warnings

---

src/App.scss
src/messages/workflows.messages.js
src/smart-components/workflow/remove-workflow-modal.js
src/test/smart-components/workflow/remove-workflow-modal.test.js

- cleaner code
- splitting the message into two will help translators to understand the context better
Also cleans the one warning in the test log (elements in `formatMessage` do have to have a key)
@lgalis @Hyperkid123

Refactor remove workflow modal text

---

src/App.scss
src/presentational-components/shared/table-toolbar-view.js

The table cell content was aligned to the top instead of the center.

Fix tables vertical align

---

src/smart-components/request/action-modal.js
src/smart-components/request/requests-list.js
src/smart-components/request/requests.js
src/test/smart-components/request/requests.test.js

On the My Request list, when a request was approved or denied, the list was not refreshed, so the new state was not reflected.
https://projects.engineering.redhat.com/browse/SSP-1802

Refresh request list after approve/deny actions

---

src/smart-components/request/request-actions.js
src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap

Allow adding comments to approval requests based only on the user capabilities, regardless of the request status. This is only on the individual request detail page. The request list page will display the status for approved or denied requests.
Fixes https://issues.redhat.com/browse/SSP-2061
Before:
After:

Allow adding comments on all requests, based on capabilities

---

src/presentational-components/shared/table-toolbar-view.js
src/smart-components/request/requests-list.js
src/test/presentional-components/table-toolbar-view.test.js

Fix the toolbar to still display the search filter when the search return no results.
Clear the search filter when switching between the 2 requests tabs
Fixes https://issues.redhat.com/browse/SSP-2039

Fix empty filtered requests

---

package-lock.json
package.json

Reverts RedHatInsights/approval-ui#627  - it is causing layout issues with the filter box

Revert "Bump @redhat-cloud-services/frontend-components from 3.6.0 to 3.6.2"
